// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	REDIRECT_URI: "https://unchainadmin.pages.dev/auth/google-cb";
	DST_MAIL: string;
	TELEGRAM_TOKEN: string;
	TELEGRAM_WEBHOOK_TOKEN: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
